version: '3'

services:
  elasticsearch:
    image: elasticsearch:2.4.6
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data:ro
    networks:
      - dendro

  virtuoso:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.4
    ports:
      - "8890:8890"
      - "1111:1111"
    environment:
      - "SPARQL_UPDATE=true"
      - "VIRT_Parameters_CheckpointSyncMode=2"
      - "VIRT_Parameters_PageMapCheck=1"
      - "VIRT_Parameters_CheckpointInterval=0"
    volumes:
      - ./virtuoso:/data:ro
    networks:
      - dendro

  mysql:
    image: mysql:8.0.3
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=r00t_p4ssw0rd"
    volumes:
      - ./mysql:/var/lib/mysql:ro
    networks:
      - dendro

  mongodb:
    image: mongo:3.4.10
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db:ro
    networks:
      - dendro

  dendro:
    image: dendro:master
    ports:
      - "3001:3001"
    volumes:
      - ./dendro:/dendro/dendro:ro
    depends_on:
      - virtuoso
      - mysql
      - elasticsearch
      - mongodb
    networks:
      - dendro

networks:
  dendro: {}
